### ISSUE TITLE
Deployment process

### ISSUE THREAD

**Issue by mdabcevic** [mdabcevic/mk2#84]
### Description
Do some digging on deployment process.
By semi-finals, we should atleast have it running locally in docker.

Real hosting options to look into:

- [x] Azure (university allowance)
- [x] AWS (free trial maybe)
- [x] Vercel
- [ ] Heroku?
- [x] Fly.io

---

### To Do

- [x] test manual deploy to azure
- [x] build and push backend and frontend images to ghcr.io via actions
- [x] deploy postgres db to azure
- [x] deploy backend and frontend containers to container service app on azure
- [x] deploy redis to upstash

**Comment by mdabcevic** [comment]
# Azure

Costs and capabilities:
- free student 100$, lasts 1 year
- free 1 month trial, 200$
- Postgres: 12 months hosted for free
- Static Web Apps: always free
- Backend Azure App Service: free to a degree
- Redis: 17$ monthly per instance

---

### Option 1: Static Web Apps + Azure App Service


| Piece               | Free / low-cost SKU                                                                                                  | Why it fits                                                                                      | How to deploy from GitHub                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ------------------- | -------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| **React front-end** | **Azure Static Web Apps – Free tier** (SSL, CDN, custom domain, 100 GB/mo bandwidth)                                 | Zero runtime cost, friendly to SPAs, automatic routing to `/index.html`                          | When you create the Static Web App in the portal and point it at your repo, Azure **creates a GitHub Actions workflow** that installs Node, runs `npm run build`, and deploys. Push → build & release. [Microsoft Tech Community](https://techcommunity.microsoft.com/blog/azuredevcommunityblog/this-month-in-azure-static-web-apps--102024/4352064?utm_source=chatgpt.com)[Microsoft Learn](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-react?utm_source=chatgpt.com) |
| **.NET 9 API**      | **Azure App Service Linux – Free F1 (or Basic B1 if credit allows)** (.NET 9 GA day-0)                               | Handles HTTPS, scaling, logging; no Docker knowledge required.                                   | Create the App Service, then add the **`azure/webapps-deploy`** action in `.github/workflows/backend.yml` (see sample). GitHub Actions will `dotnet publish` and zip-deploy to the site. [Microsoft Tech Community](https://techcommunity.microsoft.com/blog/appsonazureblog/-net-9-ga-available-on-azure-app-service/4295882?utm_source=chatgpt.com)[GitHub](https://github.com/actions/starter-workflows/blob/main/deployments/azure-webapps-dotnet-core.yml?utm_source=chatgpt.com)     |
| **Postgres**        | **Azure Database for PostgreSQL Flexible Server – “free 12-month” tier** (up to 750 vCPU-hrs + 32 GB)                | Managed backups, automatic patching; the quota resets each month so it stays free within limits. | Use `az postgres flexible-server create` in a deploy script **or** provision once in the portal and store the connection string as a secret in the GitHub repo. [Microsoft Learn](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-deploy-on-azure-free-account?utm_source=chatgpt.com)                                                                                                                                                                           |
| **Redis**           | **Azure Cache for Redis Basic C0 (250 MB)** – **costs** ≈ US $17/mo, so spend credit **or** host elsewhere (see §2). | Fully managed, TLS out-of-box.                                                                   | Same pattern: provision once, add `REDIS_URL` secret; no CI step needed. [Azure](https://azure.microsoft.com/en-us/pricing/details/cache/?utm_source=chatgpt.com)                                                                                                                                                                                                                                                                                                                          |

### React → Azure Static Web Apps

```yml
# .github/workflows/frontend.yml
name: deploy-front
on:
  push:
    branches: [main]
jobs:
  build_and_deploy:
    uses: Azure/static-web-apps-deploy@v2
    with:
      azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      action: "upload"
      app_location: "/"
      output_location: "build"
```

Generated automatically when you create the Static Web App from the portal.

### .NET 9 → Azure App Service

```yml
# .github/workflows/backend.yml
name: deploy-back
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '9.0.x' }
      - run: dotnet publish -c Release -o ./publish
      - uses: Azure/webapps-deploy@v3
        with:
          app-name: my-backend-prod
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
```

The publish profile comes from the App Service portal (Download publish profile → add as secret).

## Adjusting base URLs & environment variables

|Place|What to change|Example|
|---|---|---|
|**React**|Set `VITE_API_URL` or `REACT_APP_API_URL` in the host’s dashboard. Vercel, Azure Static Web Apps, and GitHub Actions all inject those at build time.|`https://my-backend-prod.azurewebsites.net/api`|
|**.NET appsettings**|In `appsettings.Production.json`, set the database and Redis connection strings, `AllowedHosts: "*"`, and (optionally) `ASPNETCORE_URLS` to `http://0.0.0.0:8080`. Use Azure App Settings or secrets in Render/Fly.|`"ConnectionStrings": { "Default": "Host=${POSTGRES_HOST};..." }`|
|**CORS**|Add in your API project: `builder.Services.AddCors(...)` allowing the front-end host.|`https://purple-water-12345.web.app`|

During local dev keep `localhost:5173` (or create an `.env.local`), then commit only `.env.example` to remind future you which vars exist.

---

### Option 2: Container Apps


|Piece|Free / low-cost SKU|Why it fits|How to deploy from GitHub|
|---|---|---|---|
|**Frontend (React + Nginx container)**|**Azure Container Apps – Free 180K vCPU-seconds / 360K GiB-seconds / 2M requests per month**|Fully containerized, runs with HTTPS and automatic scaling. Minimal cost if scaled-to-zero. No CDN caching, but perfect for student/hobby.|GitHub Actions builds the frontend image → pushes to GHCR → deploys using `docker-compose.yml` (frontend + backend) to Azure Container Apps.|
|**Backend (.NET 9 API container)**|**Same Azure Container App (multi-container setup)**|Backend API shares the Container App with frontend. Internal proxying of `/api/*` inside Nginx — no CORS issues, same domain.|Same GitHub Actions workflow builds backend image → pushes to GHCR → deploys with frontend together via Docker Compose.|
|**Postgres**|**Azure Database for PostgreSQL Flexible Server – “free 12-month” tier** (up to 750 vCPU-hrs + 32 GB storage)|Managed database service, free for 12 months. After 12 months migrate or pay small fee.|Provision via Portal or `az postgres flexible-server create`. Store connection string securely in Azure Container App environment variables.|
|**Redis**|**Upstash Redis Free Tier (external)** or **pay ~$17/month for Azure Cache for Redis**|Use Upstash free plan to avoid Azure Redis cost. Fits hobby/student usage perfectly.|Create free Redis DB on Upstash.com. Inject Redis connection string into your backend container via Azure secrets/environment variables.|

### Example GitHub Actions flow for both containers:
```yaml
name: deploy-frontend-backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GHCR
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Frontend
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/frontend:latest ./frontend
        docker push ghcr.io/${{ github.repository_owner }}/frontend:latest

    - name: Build and Push Backend
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest ./backend
        docker push ghcr.io/${{ github.repository_owner }}/backend:latest

    - name: Deploy to Azure Container Apps (frontend)
      uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: frontend-app
        resourceGroup: your-rg
        imageToDeploy: ghcr.io/${{ github.repository_owner }}/frontend:latest
        environmentVariables: |
          VITE_API_URL=https://your-backend-url.azurecontainerapps.io/api

    - name: Deploy to Azure Container Apps (backend)
      uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: backend-app
        resourceGroup: your-rg
        imageToDeploy: ghcr.io/${{ github.repository_owner }}/backend:latest
        environmentVariables: |
          CONNECTIONSTRINGS__DEFAULT=your-db-connection
          REDIS_URL=your-redis-url
```

### Steps Overview

```
GitHub Push (main)
   ↓
GitHub Actions
   ↓
Build frontend & backend images
   ↓
Push to GHCR
   ↓
Deploy docker-compose.yml to Azure Container App
   ↓
Users access https://yourcontainerapp.azurecontainerapps.io
   ↓
Nginx serves React + proxies API calls to backend
```

**Comment by mdabcevic** [comment]
# What not to use


|Option|What it is|Why NOT recommended (in this case)|
|---|---|---|
|**Azure App Service Linux (Docker)**|Deploy your frontend and backend containers separately, each as App Services.|❌ Costs more (App Service Plan per container). Separate scaling. Double resource management.|
|**Azure Kubernetes Service (AKS)**|Full Kubernetes cluster for microservices hosting.|❌ Massive overkill for student/small app. Complex, expensive. Needs daily management.|
|**Azure Spring Apps**|Managed Spring Boot hosting (Java ecosystems).|❌ You’re using .NET + React, not Java Spring.|
|**Azure Virtual Machines (VM)**|Manual server setup: Docker, Nginx, SSL, everything.|❌ Way more work, responsibility for security, costs if you forget to shut down.|
|**Azure Functions (Serverless backend)** + Static Web App|Use Azure Functions for backend API instead of full containerized API.|❓ Possible for small serverless backend, but needs code rewrite into serverless architecture.|
|**Azure Container Instances (ACI)**|Run containers directly without scaling, just instant container runs.|❌ Great for one-off tasks, not designed for web apps. Not ideal for always-on services.|

**Comment by mdabcevic** [comment]
# Mixed cheap options

### “Cheapest-Possible” mix-and-match

|Component|Zero-cost home|Typical limits|
|---|---|---|
|Front-end|**Vercel Hobby Plan** – perfect for React; CI/CD is built-in by pushing to `main`. [Vercel](https://vercel.com/docs/plans/hobby?utm_source=chatgpt.com)|100 GB bandwidth / 100 deploys per day / hobby-use only|
|Postgres|**Neon Free Tier** (serverless, 0.5 GB storage, 5 GB egress per month). [Neon](https://neon.tech/docs/changelog/2024-07-05?utm_source=chatgpt.com)|Suspends when idle → no credit drain|
|Redis|**Upstash Free DB** (250 MB, 500 K commands / month as of Mar 2025). [Upstash: Serverless Data Platform](https://upstash.com/pricing/redis?utm_source=chatgpt.com)[Upstash: Serverless Data Platform](https://upstash.com/blog/redis-new-pricing?utm_source=chatgpt.com)||
|Back-end|• **Azure App Service F1** (keep credit) **or** • **Fly.io free 256 MB VM** if you prefer container deployment. [Fly](https://fly.io/docs/about/pricing/?utm_source=chatgpt.com)||

This combo is popular for students because the “expensive” pieces (Postgres & Redis) are truly free, while the API can sit on either Azure’s free tier or a tiny Fly.io machine.

---

### Everything-container on Fly.io (totally free, no Azure credit)

Fly gives ~3 shared-CPU VMs & 160 GB-hours storage/month at no charge, enough for:

- 1 small VM running your .NET API
- 1 Fly Postgres cluster (single-node, shared CPU)
- 1 Redis container (self-hosted or Upstash add-on)

Great learning experience with Docker, but you do all ops tasks (backups, updates).

**Comment by mdabcevic** [comment]
# Fly.io (successor to Heroku?)


|Piece|Free / low-cost SKU|Why it fits|How to deploy from GitHub|
|---|---|---|---|
|**Frontend (React + Nginx container)**|**Fly.io App (free tier)** — 1 shared-CPU 256MB instance free|Runs globally close to users, HTTPS auto, zero cost unless scaling heavily|GitHub Actions: build Docker image, push to Fly, or deploy directly from repo using Fly CLI|
|**Backend (.NET 9 API container)**|**Fly.io App (free tier)** — another 256MB instance free|Containerized backend API, HTTPS enabled by default|Same GitHub Actions process or manual deploy via Fly CLI|
|**Postgres**|**Fly.io Postgres Free (1 shared CPU, 1GB RAM, 3GB disk)** — first volume free|Fully managed Postgres cluster per region; simple CLI deploy|`fly postgres create` command provisions a Postgres database|
|**Redis**|**Use Upstash Free Plan (external)**|No Fly-hosted Redis, but Upstash free plan (500K commands, 256MB) fits perfectly|Provision Upstash DB, connect via REDIS_URL environment variable|


# 📦 FLY.IO RESOURCE LIMITS (Free Tier)

|Resource|Limit|
|---|---|
|CPU|3 shared-CPU instances free (~2 x 256MB + 1 x DB)|
|RAM|256MB per free instance|
|Bandwidth|3GB outbound/month|
|Storage (Postgres)|3GB disk free|
|Redis|External (use Upstash free plan)|

✅ For your current project — **well inside limits**.

---

# 📈 When would Fly.io start costing money?

|Situation|Cost|
|---|---|
|Need more than 3 instances|$2–3/month per extra|
|Need more RAM per instance|~$2–5/month to upgrade|
|Heavy bandwidth usage|Pay-as-you-go after 3GB outbound|
|Larger Postgres DB|Pay to increase disk size|

⚡ Very affordable even after free tier if app grows.


---

### GitHub Actions Workflow for Full Deploy


```yml
name: Fly.io Deploy Frontend and Backend

on:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v4

    - name: Install Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy Frontend App
      run: flyctl deploy --remote-only --config fly.toml
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    needs: deploy-frontend
    steps:
    - uses: actions/checkout@v4

    - name: Install Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy Backend App
      run: flyctl deploy --remote-only --config fly.toml
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```


### Flow Visual Summary

```
Push to GitHub
  ↓
GitHub Actions
  ↓
Install Fly CLI
  ↓
Deploy frontend (React+Nginx) container to Fly.io
  ↓
Deploy backend (ASP.NET 9 API) container to Fly.io
  ↓
Frontend talks to backend via HTTPS → no CORS issues
  ↓
Backend talks to Postgres securely
```

**Comment by mdabcevic** [comment]
# AWS


|Piece|Free / low-cost SKU|Why it fits|How to deploy from GitHub|
|---|---|---|---|
|**Frontend (React + Nginx container)**|**Elastic Beanstalk (multi-container Docker)** – 12 months free for t2.micro/t3.micro|Elastic Beanstalk abstracts EC2 + ALB + Load balancing for you; just ship a Docker Compose setup|GitHub Actions: build Docker image(s), push to ECR (AWS Container Registry), deploy via AWS CLI (Beanstalk environment)|
|**Backend (.NET 9 API container)**|**Same Beanstalk multi-container app**|Deployed together with frontend OR split into separate Beanstalk environments if needed|Same as frontend deploy if bundled; separate workflow if split|
|**Postgres**|**Amazon RDS Free Tier (12 months)** — db.t3.micro, 20GB storage|Fully managed Postgres, free 12 months for students|Provision via AWS Console or Terraform/CLI; inject DB URL into Beanstalk environment|
|**Redis**|**Amazon ElastiCache Redis (only free in limited regions)** or external Upstash|Amazon Redis **not free everywhere**; better to use Upstash for free Redis at this scale|Provision externally (Upstash.com) and inject REDIS_URL into Beanstalk environment|

### Strategy


|Decision|Recommendation|
|---|---|
|Frontend and Backend|✅ Use Elastic Beanstalk multi-container setup|
|Database|✅ Use Amazon RDS Free Postgres|
|Redis|⚠️ Use Upstash external Redis (Amazon Redis not reliably free)|
|Domain|Free domain if you use your own; HTTPS via ACM|
|Secrets|✅ Store in Elastic Beanstalk Environment Variables|
|CI/CD|GitHub Actions: build images → push to ECR → deploy to Beanstalk via AWS CLI|


### Limitations


|Resource|Limit (12 months)|
|---|---|
|EC2 (Beanstalk instances)|750 hours/month (t2.micro or t3.micro)|
|RDS Postgres|750 hours/month + 20GB storage|
|S3 Storage (static files or backups)|5GB free|
|ECR (Elastic Container Registry)|500MB storage free|
|Data Transfer (bandwidth)|15GB outbound/month|


### GitHub Actions Workflow

```yml
name: AWS Deploy Frontend and Backend

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push frontend image
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_FRONTEND_REPOSITORY }}:latest ./frontend
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_FRONTEND_REPOSITORY }}:latest

    - name: Build, tag, and push backend image
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_BACKEND_REPOSITORY }}:latest ./backend
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_BACKEND_REPOSITORY }}:latest

    - name: Deploy to Elastic Beanstalk
      run: |
        eb init ${{ secrets.APPLICATION_NAME }} --platform "Docker running on 64bit Amazon Linux 2" --region ${{ secrets.AWS_REGION }}
        eb deploy ${{ secrets.BEANSTALK_ENVIRONMENT_NAME }}

```


### Final Flow Visual Overview:


```
Push to GitHub
  ↓
GitHub Actions
  ↓
Docker build + push to ECR (frontend + backend)
  ↓
Elastic Beanstalk deploys docker-compose.yml
  ↓
Frontend container exposed via Load Balancer
Backend container runs inside Beanstalk
  ↓
Backend connects to RDS Postgres
Frontend connects to backend via HTTPS
```
